version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    ports:
      - "5173:5173"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    name: my_network
